package land.oz.munchkin.marincloud.common.item.build_in

/**
 * Created by CowardlyLion at 2022/7/15 21:43
 */
object ItemNamesSword {

    const val longhuang = "longhuang"

    const val sword_0 = "sword_0"
    const val sword_1 = "sword_1"
    const val sword_2 = "sword_2"
    const val sword_3 = "sword_3"
    const val sword_4 = "sword_4"
    const val sword_5 = "sword_5"
    const val sword_6 = "sword_6"
    const val sword_7 = "sword_7"
    const val sword_8 = "sword_8"
    const val sword_9 = "sword_9"
    const val sword_10 = "sword_10"
    const val sword_11 = "sword_11"
    const val sword_12 = "sword_12"
    const val sword_13 = "sword_13"
    const val sword_14 = "sword_14"
    const val sword_15 = "sword_15"
    const val sword_16 = "sword_16"
    const val sword_17 = "sword_17"
    const val sword_18 = "sword_18"
    const val sword_19 = "sword_19"
    const val sword_20 = "sword_20"
    const val sword_21 = "sword_21"
    const val sword_22 = "sword_22"
    const val sword_23 = "sword_23"
    const val sword_24 = "sword_24"
    const val sword_25 = "sword_25"
    const val sword_26 = "sword_26"
    const val sword_27 = "sword_27"
    const val sword_28 = "sword_28"
    const val sword_29 = "sword_29"
    const val sword_30 = "sword_30"
    const val sword_31 = "sword_31"
    const val sword_32 = "sword_32"
    const val sword_33 = "sword_33"
    const val sword_34 = "sword_34"
    const val sword_35 = "sword_35"
    const val sword_36 = "sword_36"
    const val sword_37 = "sword_37"
    const val sword_38 = "sword_38"
    const val sword_39 = "sword_39"
    const val sword_40 = "sword_40"
    const val sword_41 = "sword_41"
    const val sword_42 = "sword_42"
    const val sword_43 = "sword_43"
    const val sword_44 = "sword_44"
    const val sword_45 = "sword_45"
    const val sword_46 = "sword_46"
    const val sword_47 = "sword_47"
    const val sword_48 = "sword_48"
    const val sword_49 = "sword_49"
    const val sword_50 = "sword_50"

}